name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Jello World!"
      - name: Print goodbye
        run: echo "Goodbye Cruel World!"
